### PR TITLE
Add .sh to install master binaries

### PR DESCRIPTION
**Pull request by michgauz**

### CODE REVIEW

**Comment by michgauz** [comment]
Not sure where I should modify the github.io index.
Here : https://github.com/dailymotion/kinta/blob/gh-pages/index.html ?

**Review by martinbonnin — APPROVED** [review]
This duplicates a bit of shell scripts but I don't really see a way around that. I'd call that script `install_snapshot.sh` as said in the other PR but up to you.

**Comment by martinbonnin** [comment]
https://github.com/dailymotion/kinta/blob/gh-pages/index.html is generated automagically from `README.md` so if you made the change there, it will be displayed in github pages.

**Comment by martinbonnin** [comment]
Sorry I didn't see this PR was made agains `gh-pages`. I think it will be overwritten automatically by the docs deploy. If that happens, you can add the `install_snapshot.sh` at https://github.com/dailymotion/kinta/tree/master/docs

**Pull request merged**
